### PR TITLE
X910 dependency update

### PR DESCRIPTION
**Pull request by seenanair**
Dependency updates on SPrint client

### CODE REVIEW

**Comment by khelwood** [comment]
When I try to run yarn, I get
error @apollo/federation@0.27.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <17.0". Got "18.7.0"
error Found incompatible module.

Do you know how to address this? Do I need to run an earlier version of node?

**Comment by seenanair** [comment]
> When I try to run yarn, I get error @apollo/federation@0.27.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <17.0". Got "18.7.0" error Found incompatible module.
> 
> Do you know how to address this? Do I need to run an earlier version of node?

The previous git node version was 14.19.3
But, now it is changed to 18.7 and it seems to be working in mine. Would you please try a 'yarn install'?

**Comment by khelwood** [comment]
image

**Comment by seenanair** [comment]
> image

I have made a PR with a change in workflow to get the node version from .nvmrc file. Would you please try whether that helps?

**Comment by khelwood** [comment]
A change in the `.github/workflow` will not affect what happens when I try to run the client locally.

**Comment by seenanair** [comment]
> image



> A change in the `.github/workflow` will not affect what happens when I try to run the client locally.
@apollo/federation package has not been explicitly included in package.json. But when I checked 
Screenshot 2022-08-03 at 18 09 10
the documentation it says, the package supports only Node 14 or Node 16.

**Comment by seenanair** [comment]
But I don't understand why it is not giving an error in mine. I am running SPrint server using docker image and I can see it is up and running
Screenshot 2022-08-03 at 18 12 32

**Comment by seenanair** [comment]
Would you please change the node version and see whether that helps to Node 14.x

**Comment by khelwood** [comment]
> Would you please change the node version and see whether that helps to Node 14.x? Also, can you try removing all node_modules by _rm -r node_modules/_ and then _yarn install_

I don't have any `node_modules` directory. Perhaps you can show me tomorrow how to run it with the correct node version.

**Comment by seenanair** [comment]
> > Would you please change the node version and see whether that helps to Node 14.x? Also, can you try removing all node_modules by _rm -r node_modules/_ and then _yarn install_
> 
> I don't have any `node_modules` directory. Perhaps you can show me tomorrow how to run it with the correct node version.

Sure, we can do that tomorrow.

**Comment by khelwood** [comment]
I used `yarn install --ignore-engines` to avoid the errors.

**Review by khelwood — APPROVED** [review]

**Pull request merged**
